source "https://rubygems.org"

gem "jekyll", "~> 4.4"
gem "jekyll-asciidoc", "~> 3.0"
gem "jekyll-feed", "~> 0.17"
gem "jekyll-seo-tag", "~> 2.8"
gem "jekyll-sitemap", "~> 1.4"
gem "webrick", "~> 1.9"
gem "tzinfo", ">= 1", "< 3"
gem "tzinfo-data"
